# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: itescia

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  builder:
    image: maven:3.3-jdk-8
    command: mvn clean install
    volumes:
      - .:/usr/src/mymaven
    working_dir: /usr/src/mymaven

  launcher:
    image: maven:3.3-jdk-8
    command: mvn spring-boot:run
    depends_on:
      - builder
    volumes:
      - .:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    ports:
      - 8080:8080

  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./mavenkey.conf:/launcher/mavenkey.conf
    depends_on:
      - launcher
